### ISSUE TITLE
`!=` crashes the vm

### ISSUE THREAD

**Issue by MinekPo1** [Its-Jakey/SCPP#12]
Steps to reproduce:

1. use `!=` in your code
2. compile with the `-r` flag

Expected behavior:

The vm not crashing.

Actual behavior:

The vm crashes.

<details><summary>Error trace</summary>

```
Exception in thread "main" slvm.VMException: Unknown instruction 'boolNotEqualWithVar'
        at ..\PySCPP\test.slvm.txt:15
        at null:0
        at null:0
        at slvm.SLVM.execute(SLVM.java:402)
        at slvm.SLVM.run(SLVM.java:193)
        at main.Main.main(Main.java:61)
```
</summary>

**Comment by Its-Jakey** [comment]
Fixed in v0.1
