### ISSUE TITLE
IDE unable to open config file on Windows

### ISSUE THREAD

**Issue by MinekPo1** [Its-Jakey/SCPP#17]
The editor tries to open `\home\<User>\.scppide\config.txt`, which does not exist.

The proper path is `C:\Users\<User>\.scppide\config.txt`.

**Comment by Its-Jakey** [comment]
Hmm, do you have a stack trace for the Exception?

**Comment by MinekPo1** [comment]
Sorry! Here it is:

```
java.nio.file.NoSuchFileException: \home\<user>\.scppide\config.txt
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.write(Files.java:3512)
        at java.base/java.nio.file.Files.writeString(Files.java:3734)
        at java.base/java.nio.file.Files.writeString(Files.java:3674)
        at ide.Config.writeToFile(Config.java:43)
        at ide.Ide.getDefaultConfig(Ide.java:46)
        at ide.Ide.createProperInstance(Ide.java:156)
        at main.Main.main(Main.java:54)
```

Edit: removed deadname. oops

**Comment by Its-Jakey** [comment]
Could you run the code `System.out.println(System.getProperty("user.home"));` and tell me the output?

**Comment by MinekPo1** [comment]
~~I would love to do so, but I have no idea how to compile and run java source code.~~

~~I tried `javac <fname>.java` followed by `java <fname>`, but it didn't work :/~~

Edit: turns out I have to ADD THE CURRENT DIRECTORY TO THE CLASS PATH wtf is this language???

Anyway it is `C:\Users\<user>`

**Comment by MinekPo1** [comment]
Maybe consider using a sys var to configure the config files location?

**Comment by Its-Jakey** [comment]
> ~I would love to do so, but I have no idea how to compile and run java source code.~
> 
> ~I tried `javac <fname>.java` followed by `java <fname>`, but it didn't work :/~
> 
> Edit: turns out I have to ADD THE CURRENT DIRECTORY TO THE CLASS PATH wtf is this language???
> 
> Anyway it is `C:\Users\<user>`

That is so odd, the path to the home folder is correct. I have no idea why it wouldn't be working.
